version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # FIXED: Use service name instead of localhost
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=Elasticsearch@123
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  log-consumer-1:
    image: node:18
    working_dir: '/host_mnt/c/Users/tanis/Log Micro Service'
    volumes:
      - '/host_mnt/c/Users/tanis/Log Micro Service:/app'
    command: ["sh", "-c", "until nc -z kafka 9092; do echo waiting for kafka; sleep 5; done; node /app/config/consumer.js"]
    environment:
      - KAFKA_BROKER=kafka:9092  # FIXED: Use `kafka` instead of `localhost`
      - KAFKA_TOPIC=logs
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=Elasticsearch@123
    depends_on:
      - kafka

  log-consumer-2:
    image: node:18
    working_dir: '/host_mnt/c/Users/tanis/Log Micro Service'
    volumes:
      - '/host_mnt/c/Users/tanis/Log Micro Service:/app'
    command: ["node", "/app/config/consumer.js"]
    environment:
      - KAFKA_BROKER=kafka:9092  # FIXED: Use `kafka` instead of `localhost`
      - KAFKA_TOPIC=logs
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=Elasticsearch@123
    depends_on:
      - kafka
